// changesDir -> 1 = "up" & 0 = "down"
export const rankings = [
  {
    Rank: 1,
    Name: "rakesh Sharma",
    Designation: "UI/UX designer",
    Hours: "7(42)",
    Changes: 1.5,
    ChangesDir: 1,
    image: "https://xsgames.co/randomusers/assets/avatars/male/66.jpg",
  },
  {
    Rank: 2,
    Name: "Ankita Thakur",
    Designation: "HR Recruiter",
    Hours: "7(41)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/female/46.jpg",
  },
  {
    Rank: 3,
    Name: "Sarah Yadav",
    Designation: "Product Manager",
    Hours: "7(40)",
    Changes: 1.5,
    ChangesDir: 1,
    image: "https://xsgames.co/randomusers/assets/avatars/male/20.jpg",
  },
  {
    Rank: 4,
    Name: "Harsha Shivhare",
    Designation: "Designer",
    Hours: "7(37)",
    Changes: 1.5,
    ChangesDir: 1,
    image: "https://xsgames.co/randomusers/assets/avatars/female/39.jpg",
  },
  {
    Rank: 5,
    Name: "Vanhi Rai",
    Designation: "Video Editor",
    Hours: "7(37)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/49.jpg",
  },
  {
    Rank: 6,
    Name: "Bhanu Sharma",
    Designation: "Business Analyst",
    Hours: "7(32)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/31.jpg",
  },
  {
    Rank: 7,
    Name: "Sunil Yadav",
    Designation: "Developer",
    Hours: "7(24)",
    Changes: 1.5,
    ChangesDir: 1,
    image: "https://xsgames.co/randomusers/assets/avatars/male/61.jpg",
  },
  {
    Rank: 8,
    Name: "Akash Roy",
    Designation: "Business Analyst",
    Hours: "7(21)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/23.jpg",
  },
  {
    Rank: 9,
    Name: "Rohit Soni",
    Designation: "Developer",
    Hours: "7(20)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/67.jpg",
  },
  {
    Rank: 10,
    Name: "Suraj Chauhan",
    Designation: "Developer",
    Hours: "7(18)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/20.jpg",
  },
  {
    Rank: 11,
    Name: "Anurag Chaudari",
    Designation: "Developer",
    Hours: "7(16)",
    Changes: 1.5,
    ChangesDir: 0,
    image: "https://xsgames.co/randomusers/assets/avatars/male/10.jpg",
  },
];
